// Mapeo principio_activo -> categoría, generado a partir de la
// clasificación curada en db/seed_medicamentos.csv (fase 1 del proyecto,
// no inventada aquí). Cubre los ~195 principios activos originales de la
// semilla; el catálogo real scrapeado tiene más principios que no matchean
// ninguna categoría — esos simplemente no aparecen en la cuadrícula de
// categorías, siguen siendo buscables por texto libre.
const PRINCIPIO_A_CATEGORIA: Record<string, string> = {
  enalapril: "hipertension",
  captopril: "hipertension",
  lisinopril: "hipertension",
  ramipril: "hipertension",
  perindopril: "hipertension",
  "enalapril/hidroclorotiazida": "hipertension",
  "captopril/hidroclorotiazida": "hipertension",
  losartan: "hipertension",
  "losartan/hidroclorotiazida": "hipertension",
  valsartan: "hipertension",
  "valsartan/hidroclorotiazida": "hipertension",
  telmisartan: "hipertension",
  "telmisartan/hidroclorotiazida": "hipertension",
  irbesartan: "hipertension",
  olmesartan: "hipertension",
  candesartan: "hipertension",
  amlodipino: "hipertension",
  "nifedipino retard": "hipertension",
  "losartan/amlodipino": "hipertension",
  "amlodipino/valsartan": "hipertension",
  verapamilo: "hipertension",
  diltiazem: "hipertension",
  "diltiazem retard": "hipertension",
  atenolol: "hipertension",
  "metoprolol tartrato": "hipertension",
  "metoprolol succinato retard": "hipertension",
  bisoprolol: "hipertension",
  carvedilol: "hipertension",
  propranolol: "hipertension",
  nebivolol: "hipertension",
  hidroclorotiazida: "hipertension",
  furosemida: "hipertension",
  espironolactona: "hipertension",
  indapamida: "hipertension",
  clortalidona: "hipertension",
  clonidina: "hipertension",
  doxazosina: "hipertension",
  prazosina: "hipertension",
  metildopa: "hipertension",
  metformina: "diabetes",
  "metformina liberacion prolongada": "diabetes",
  glibenclamida: "diabetes",
  glimepirida: "diabetes",
  "glimepirida/metformina": "diabetes",
  gliclazida: "diabetes",
  sitagliptina: "diabetes",
  "sitagliptina/metformina": "diabetes",
  vildagliptina: "diabetes",
  "vildagliptina/metformina": "diabetes",
  linagliptina: "diabetes",
  saxagliptina: "diabetes",
  empagliflozina: "diabetes",
  dapagliflozina: "diabetes",
  "dapagliflozina/metformina": "diabetes",
  pioglitazona: "diabetes",
  acarbosa: "diabetes",
  repaglinida: "diabetes",
  "insulina glargina": "diabetes",
  "insulina nph": "diabetes",
  "insulina cristalina": "diabetes",
  "insulina lispro": "diabetes",
  "insulina aspart": "diabetes",
  "insulina mezcla 70/30": "diabetes",
  "insulina degludec": "diabetes",
  "insulina glulisina": "diabetes",
  "insulina detemir": "diabetes",
  "glibenclamida/metformina": "diabetes",
  canagliflozina: "diabetes",
  liraglutida: "diabetes",
  semaglutida: "diabetes",
  "tiras reactivas glucosa": "diabetes",
  levotiroxina: "tiroides",
  metimazol: "tiroides",
  propiltiouracilo: "tiroides",
  atorvastatina: "colesterol",
  rosuvastatina: "colesterol",
  simvastatina: "colesterol",
  pravastatina: "colesterol",
  lovastatina: "colesterol",
  ezetimiba: "colesterol",
  "ezetimiba/atorvastatina": "colesterol",
  "ezetimiba/simvastatina": "colesterol",
  fenofibrato: "colesterol",
  gemfibrozilo: "colesterol",
  bezafibrato: "colesterol",
  colestiramina: "colesterol",
  "omega 3 aceite de pescado": "colesterol",
  "atorvastatina/amlodipino": "colesterol",
  "rosuvastatina/ezetimiba": "colesterol",
  evolocumab: "colesterol",
  "acido nicotinico": "colesterol",
  pitavastatina: "colesterol",
  amoxicilina: "antibiotico",
  "amoxicilina/acido clavulanico": "antibiotico",
  azitromicina: "antibiotico",
  claritromicina: "antibiotico",
  ciprofloxacino: "antibiotico",
  levofloxacino: "antibiotico",
  moxifloxacino: "antibiotico",
  norfloxacino: "antibiotico",
  cefalexina: "antibiotico",
  cefadroxilo: "antibiotico",
  cefuroxima: "antibiotico",
  cefixima: "antibiotico",
  ceftriaxona: "antibiotico",
  "trimetoprim/sulfametoxazol": "antibiotico",
  doxiciclina: "antibiotico",
  clindamicina: "antibiotico",
  metronidazol: "antibiotico",
  nitrofurantoina: "antibiotico",
  "fosfomicina trometamol": "antibiotico",
  "penicilina benzatinica": "antibiotico",
  ampicilina: "antibiotico",
  dicloxacilina: "antibiotico",
  eritromicina: "antibiotico",
  gentamicina: "antibiotico",
  amikacina: "antibiotico",
  nistatina: "antibiotico",
  "penicilina v": "antibiotico",
  tetraciclina: "antibiotico",
  rifampicina: "antibiotico",
  "sulfadiazina de plata": "antibiotico",
  cefpodoxima: "antibiotico",
  vancomicina: "antibiotico",
  meropenem: "antibiotico",
  paracetamol: "analgesico_antiinflamatorio",
  "paracetamol/cafeina": "analgesico_antiinflamatorio",
  ibuprofeno: "analgesico_antiinflamatorio",
  "ibuprofeno/paracetamol": "analgesico_antiinflamatorio",
  "diclofenaco sodico": "analgesico_antiinflamatorio",
  "diclofenaco potasico": "analgesico_antiinflamatorio",
  diclofenaco: "analgesico_antiinflamatorio",
  naproxeno: "analgesico_antiinflamatorio",
  "naproxeno sodico": "analgesico_antiinflamatorio",
  ketorolaco: "analgesico_antiinflamatorio",
  "acido acetilsalicilico": "analgesico_antiinflamatorio",
  meloxicam: "analgesico_antiinflamatorio",
  celecoxib: "analgesico_antiinflamatorio",
  etoricoxib: "analgesico_antiinflamatorio",
  tramadol: "analgesico_antiinflamatorio",
  "tramadol/paracetamol": "analgesico_antiinflamatorio",
  "metamizol sodico": "analgesico_antiinflamatorio",
  piroxicam: "analgesico_antiinflamatorio",
  dexketoprofeno: "analgesico_antiinflamatorio",
  nimesulida: "analgesico_antiinflamatorio",
  aceclofenaco: "analgesico_antiinflamatorio",
  indometacina: "analgesico_antiinflamatorio",
  flurbiprofeno: "analgesico_antiinflamatorio",
  ketoprofeno: "analgesico_antiinflamatorio",
  etodolaco: "analgesico_antiinflamatorio",
  "naproxeno/paracetamol": "analgesico_antiinflamatorio",
  "diclofenaco/vitaminas b1-b6-b12": "analgesico_antiinflamatorio",
  "acido mefenamico": "analgesico_antiinflamatorio",
  "etinilestradiol/levonorgestrel": "anticonceptivo",
  "etinilestradiol/levonorgestrel trifasico": "anticonceptivo",
  "etinilestradiol/drospirenona": "anticonceptivo",
  "etinilestradiol/gestodeno": "anticonceptivo",
  "etinilestradiol/ciproterona": "anticonceptivo",
  "etinilestradiol/desogestrel": "anticonceptivo",
  "etinilestradiol/clormadinona": "anticonceptivo",
  "norgestrel/etinilestradiol": "anticonceptivo",
  desogestrel: "anticonceptivo",
  "levonorgestrel emergencia": "anticonceptivo",
  medroxiprogesterona: "anticonceptivo",
  "estradiol/medroxiprogesterona": "anticonceptivo",
  etonogestrel: "anticonceptivo",
  "etinilestradiol/norelgestromina": "anticonceptivo",
  "etonogestrel/etinilestradiol": "anticonceptivo",
  "drospirenona sola": "anticonceptivo",
  linestrenol: "anticonceptivo",
  "etinilestradiol/dienogest": "anticonceptivo",
  "noretisterona enantato/estradiol valerato": "anticonceptivo",
  omeprazol: "gastritis",
  esomeprazol: "gastritis",
  pantoprazol: "gastritis",
  lansoprazol: "gastritis",
  rabeprazol: "gastritis",
  famotidina: "gastritis",
  sucralfato: "gastritis",
  "hidroxido de aluminio/magnesio": "gastritis",
  domperidona: "gastritis",
  metoclopramida: "gastritis",
  "bismuto subsalicilato": "gastritis",
  simeticona: "gastritis",
  butilhioscina: "gastritis",
  "butilhioscina/paracetamol": "gastritis",
  "carbonato de calcio": "gastritis",
  "terapia triple h. pylori (omeprazol/amoxicilina/claritromicina)": "gastritis",
  loperamida: "gastritis",
  racecadotrilo: "gastritis",
  "sales de rehidratacion oral": "gastritis",
  "alginato de sodio/antiacido": "gastritis",
  lactulosa: "gastritis",
  trimebutina: "gastritis",
  dimenhidrinato: "gastritis",
};

export type CategoriaMeta = {
  slug: string;
  nombre: string;
  color: string;
  colorBg: string;
  // path de un ícono simple de trazo (stroke), dibujado a mano, sin
  // librería de iconos externa — ver Boveda Farmacia/Conceptos/Diseño web.
  icon: string;
};

export const CATEGORIAS: CategoriaMeta[] = [
  { slug: "hipertension", nombre: "Hipertensión", color: "#8c3a4f", colorBg: "#f3e4e7", icon: "heart" },
  { slug: "diabetes", nombre: "Diabetes", color: "#2d5f8a", colorBg: "#e2eaf1", icon: "droplet" },
  { slug: "antibiotico", nombre: "Antibióticos", color: "#1f6b52", colorBg: "#dfeee8", icon: "shield" },
  { slug: "analgesico_antiinflamatorio", nombre: "Dolor y Fiebre", color: "#b3721f", colorBg: "#f4e8d4", icon: "bolt" },
  { slug: "gastritis", nombre: "Gastritis y Digestión", color: "#75701f", colorBg: "#eeecda", icon: "leaf" },
  { slug: "colesterol", nombre: "Colesterol", color: "#6b3f8a", colorBg: "#ecdff1", icon: "drop" },
  { slug: "anticonceptivo", nombre: "Anticonceptivos", color: "#a8386b", colorBg: "#f4dfe9", icon: "calendar" },
  { slug: "tiroides", nombre: "Tiroides", color: "#1f7a94", colorBg: "#dcedf1", icon: "target" },
];

export function categoriaDe(principioActivo: string): string | null {
  const key = principioActivo.trim().toLowerCase();
  return PRINCIPIO_A_CATEGORIA[key] ?? null;
}

export function categoriaMeta(slug: string): CategoriaMeta | undefined {
  return CATEGORIAS.find((c) => c.slug === slug);
}
